### ISSUE TITLE
NullPointerException in the sample app

### ISSUE THREAD

**Issue by wenris** [DevAhamed/MultiViewAdapter#21]
In 'Simple grid' and 'Complex' page, long press the grid item will caused `NullPointerException`:

```
FATAL EXCEPTION: main
    Process: com.ahamed.sample, PID: 25712
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.helper.ItemTouchHelper.startDrag(android.support.v7.widget.RecyclerView$ViewHolder)' on a null object reference
    at com.ahamed.multiviewadapter.CoreRecyclerAdapter$2.onStartDrag(CoreRecyclerAdapter.java:79)
    at com.ahamed.multiviewadapter.BaseViewHolder.startDrag(BaseViewHolder.java:162)
    at com.ahamed.sample.common.binder.GridItemBinder$ItemViewHolder$2.onItemLongClick(GridItemBinder.java:73)
    at com.ahamed.sample.common.binder.GridItemBinder$ItemViewHolder$2.onItemLongClick(GridItemBinder.java:71)
    at com.ahamed.multiviewadapter.BaseViewHolder.onLongClick(BaseViewHolder.java:44)
```

**Comment by DevAhamed** [comment]
The library has been refactored and 2.x has been released. If you are still facing this issue kindly re-open.
