### ISSUE TITLE
Kotlin IllegalAccessError Problem

### ISSUE THREAD

**Issue by HarryTylenol** [DevAhamed/MultiViewAdapter#26]
I got IllegalAccessError when my RecyclerAdapter is Kotlin.
It says "Illegal class access", "declaration of 'My Adapter Class' appears in ...base.apk:classes2.dex"

But when I change my class to java, It works fine.

```
java.lang.IllegalAccessError: Illegal class access: 'cupid.android.ui.adapter.HomeFragmentAdapter' attempting to access 'com.ahamed.multiviewadapter.BaseDataManager' (declaration of 'cupid.android.ui.adapter.HomeFragmentAdapter' appears in /data/app/cupid.android-1/base.apk:classes2.dex)
                                                                 at cupid.android.ui.adapter.HomeFragmentAdapter.<init>(HomeFragmentAdapter.kt:20)
                                                                 at cupid.android.ui.screen.activity.main.fragment.home.HomeFragmentLayout.createView(HomeFragmentLayout.kt:20)
                                                                 at cupid.android.ui.screen.activity.main.fragment.home.HomeFragmentLayout.createView(HomeFragmentLayout.kt:13)
                                                                 at cupid.android.ui.base.BaseFragmentLayout.view(BaseFragmentLayout.kt:12)
                                                                 at cupid.android.ui.screen.activity.main.fragment.home.HomeFragment.onCreateView(HomeFragment.kt:37)
                                                                 at android.support.v4.app.Fragment.performCreateView(Fragment.java:2337)
                                                                 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
                                                                 at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1739)
                                                                 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1808)
                                                                 at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
                                                                 at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2579)
                                                                 at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2366)
                                                                 at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2321)
                                                                 at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2198)
                                                                 at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:651)
                                                                 at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:167)
                                                                 at android.support.v4.view.ViewPager.populate(ViewPager.java:1236)
                                                                 at android.support.v4.view.ViewPager.populate(ViewPager.java:1084)
                                                                 at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1614)
                                                                 at android.view.View.measure(View.java:19857)
                                                                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                 at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:714)
                                                                 at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:91)
                                                                 at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1362)
                                                                 at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:784)
                                                                 at android.view.View.measure(View.java:19857)
                                                                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                 at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                 at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                 at android.view.View.measure(View.java:19857)
                                                                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                 at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                 at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                 at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                 at android.view.View.measure(View.java:19857)
                                                                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                 at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                 at android.view.View.measure(View.java:19857)
                                                                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                 at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                 at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                 at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                 at android.view.View.measure(View.java:19857)
                                                                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                 at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                 at com.android.internal.policy.DecorView.onMeasure(DecorView.java:689)
                                                                 at android.view.View.measure(View.java:19857)
07-06 04:36:31.822 8493-8493/cupid.android E/AndroidRuntime:     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2275)
                                                                 at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1366)
                                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1619)
                                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                 at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                 at android.os.Handler.handleCallback(Handler.java:751)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by DevAhamed** [comment]
Thanks for raising this issue. There is an open PR #23 to fix this. I am currently reviewing the PR and soon release a new version.
